# Generated by Django 6.0.6 on 2026-06-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_grupo_cobranca_automatica_grupo_dia_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrogrupo',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
