# Generated by Django 6.0.6 on 2026-06-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_membrogrupo_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='assinatura_paga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='streak_pagamentos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
