# Generated by Django 6.0.5 on 2026-06-16 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_plano_streaming'),
        ('dashboard', '0006_grupo_assinatura_paga_grupo_streak_pagamentos'),
    ]

    operations = [
    ]
