# Generated by Django 6.0.6 on 2026-06-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_membros', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
